-- AlterTable
ALTER TABLE `categories` ADD COLUMN `allowedRoles` VARCHAR(191) NOT NULL DEFAULT 'ADMIN,SECURITY_GUARD,MANAGEMENT';

-- AlterTable
ALTER TABLE `users` MODIFY `role` ENUM('ADMIN', 'SECURITY_GUARD', 'MANAGEMENT') NOT NULL DEFAULT 'SECURITY_GUARD';
